slider组件
JSON-Drived-Configurable-Platform/cp pull request #61
Opened 2020-04-02 10:55 UTC by zhang0821

slider组件

2020-04-02 10:58 UTC, zhang0821 commented
slider

2020-04-02 11:04 UTC, zhengxkq commented on src/fields/fieldSlider.vue
> +        handleInput(value) {
I think this method not use ?

2020-04-02 11:07 UTC, zhengxkq commented on src/formGenerator.vue
> +        handleFieldInput({model, value}) {
he same as above

2020-04-02 11:26 UTC, zhengxkq requested changes
I found all of handleInput method don't use, I think you can delete these method, thanks!

2020-04-03 03:31 UTC, zhengxkq approved these changes

2020-04-03 03:32 UTC, merged